### ISSUE TITLE
Remove empty constructors from Domain Model

### ISSUE THREAD

**Issue by abuzaforfagun** [abuzaforfagun/Invoice.Microservices.ThirdPartyAPIIntegration#3]
There is a couple of empty constructors in the domain models, what is used to make Automapper happy.

We can remove that empty constructor following the guideline of [auto mapper](https://docs.automapper.org/en/stable/Custom-type-converters.html).

We also can think about removing Automapper. As we are not doing any complex mapping there.

**Comment by ysnarafat** [comment]
Can work on this?

**Comment by abuzaforfagun** [comment]
Sure, you are most welcome.

I was thinking about removing the AutoMapper and create the object using the parameterized constructor.
I appreciate if you can do that and create a PR.

**Comment by ysnarafat** [comment]
Ok, I will do accordingly.
